baseurl = "about/"
relativeurls = true
languageCode = "en-us"
title = "Rebecca Barter"
theme = "hugo-future-imperfect"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/post/"
[[menu.main]]
    name = "CV"
    url = "/cv/"
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rlbarter"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rlbarter"

[params]
    description = "Data meets narative"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

